---
title: "5 quick data visualizations using the Lahman R package"
output: html_notebook
---

Not only is this an example of the ease which open source programming can be implemented, it is also blatant plagiarism of the Lahaman vignettes. 

Open source awesome sauce.

```{r}
## Install Lahman
# install.packages("Lahman")
```

```{r}
library("dplyr")
data(Batting, package="Lahman")
head(Batting) #take a look at the data
```

```{r}
batting <- Batting %>% 
  # select the variables that we want left after we filter the data
  select(yearID, H, X2B, X3B, HR) %>%
  # select the years from 1871+
  filter(yearID >= 1871) %>% 
  group_by(yearID) %>%
#  summarise_each(funs(sum(., na.rm=TRUE))) %>% 
  summarise_all(funs(sum(., na.rm=TRUE))) %>% 
  # we summarize by year, and then na.rm takes care of 0's in the data
  mutate(X1 = H-(X2B+X3B+HR)) %>% #create a column for singles
  # we eventually want these as a percentage of hits, so we can do the math now 
  mutate(Single = X1/H*100) %>% 
  mutate(Double = X2B/H*100) %>% 
  mutate(Triple = X3B/H*100) %>% 
  mutate(HomeRun = HR/H*100) %>% 
  glimpse()
```

```{r}

```






